#!/bin/bash

cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF -DCMAKE_BUILD_TYPE=Debug -DENABLE_STATIC=ON -DRT_LIBRARY=/usr/lib/x86_64-linux-gnu/librt.a -DENABLE_ZLIB=OFF -DENABLE_SASL=OFF -DENABLE_SNAPPY=OFF -DENABLE_SSL=AUTO -DENABLE_SRV=OFF -DENABLE_SHM_COUNTERS=OFF -DENABLE_RDTSCP=OFF -DENABLE_TESTS=OFF -DOPENSSL_LIBRARIES=/usr/local/ssl/lib -DOPENSSL_ROOT_DIR=/usr/local/ssl -DENABLE_TRACING=ON ..
